-- MediNova bootstrap part 3 of 3.
-- Run parts 1, 2, 3 IN ORDER in the Supabase SQL Editor. Run each part exactly once.
-- Generated by scripts/build-bootstrap.mjs - do not edit by hand.

-- ======== seed_01_catalog.sql ========
-- MediNova Module 2 seed (part 1/2): branches + departments.
-- Idempotent: safe to re-run (upserts on slug / name+medicine_type).

insert into public.branches (slug, name, name_bn, address, address_bn, city, lat, lng, phone, emergency_phone, email, opening_hours, facilities, photo_url, is_active)
values
  ('uttara', 'MediNova Uttara', 'মেডিনোভা উত্তরা', 'House 7, Road 11, Sector 4, Uttara, Dhaka 1230', 'হাউস ৭, রোড ১১, সেক্টর ৪, উত্তরা, ঢাকা ১২৩০', 'Dhaka', 23.8759, 90.3795, '+8801711000101', '16263', 'uttara@medinova.example', '{"sat-thu": "09:00-22:00", "fri": "15:00-22:00"}', '{Pharmacy,Emergency,Lab,Imaging,Cafeteria,Parking}', null, true),
  ('dhanmondi', 'MediNova Dhanmondi', 'মেডিনোভা ধানমন্ডি', 'House 12, Road 5, Dhanmondi, Dhaka 1205', 'হাউস ১২, রোড ৫, ধানমন্ডি, ঢাকা ১২০৫', 'Dhaka', 23.7461, 90.3742, '+8801711000102', '16263', 'dhanmondi@medinova.example', '{"sat-thu": "09:00-22:00", "fri": "15:00-22:00"}', '{Pharmacy,Emergency,Lab,Cabin,ICU}', null, true),
  ('gec-chattogram', 'MediNova Chattogram GEC', 'মেডিনোভা চট্টগ্রাম জিইসি', 'GEC Circle, Chattogram 4000', 'জিইসি সার্কেল, চট্টগ্রাম ৪০০০', 'Chattogram', 22.3569, 91.7832, '+8801711000103', '16263', 'gec@medinova.example', '{"sat-thu": "09:00-21:00", "fri": "15:00-21:00"}', '{Pharmacy,Emergency,Lab,Imaging}', null, true)
on conflict (slug) do update set
  name = excluded.name, name_bn = excluded.name_bn, address = excluded.address,
  address_bn = excluded.address_bn, city = excluded.city, lat = excluded.lat, lng = excluded.lng,
  phone = excluded.phone, emergency_phone = excluded.emergency_phone, email = excluded.email,
  opening_hours = excluded.opening_hours, facilities = excluded.facilities, is_active = true,
  updated_at = now();

-- 8 allopathic departments
insert into public.departments (name, name_bn, medicine_type, icon, description, is_active)
values
  ('Medicine', 'মেডিসিন', 'allopathic', 'stethoscope', 'General internal medicine', true),
  ('Cardiology', 'কার্ডিওলজি', 'allopathic', 'heart-pulse', 'Heart and hypertension care', true),
  ('Gynecology', 'গাইনী', 'allopathic', 'baby', 'Women health and pregnancy', true),
  ('Pediatrics', 'শিশুরোগ', 'allopathic', 'baby', 'Child health and immunization', true),
  ('Orthopedics', 'অর্থোপেডিক্স', 'allopathic', 'bone', 'Bones, joints and trauma', true),
  ('ENT', 'নাক-কান-গলা', 'allopathic', 'ear', 'Ear, nose and throat', true),
  ('Dermatology', 'চর্মরোগ', 'allopathic', 'sparkles', 'Skin, hair and nails', true),
  ('Neurology', 'নিউরোলজি', 'allopathic', 'brain', 'Brain, nerves and migraine', true)
on conflict (name, medicine_type) do update set
  name_bn = excluded.name_bn, icon = excluded.icon, description = excluded.description,
  is_active = true, updated_at = now();

-- 5 homeopathic departments
insert into public.departments (name, name_bn, medicine_type, icon, description, is_active)
values
  ('General Homeopathy', 'জেনারেল হোমিওপ্যাথি', 'homeopathic', 'leaf', 'Classical homeopathic consults', true),
  ('Chronic Disease', 'দীর্ঘমেয়াদি রোগ', 'homeopathic', 'activity', 'Long-term constitutional care', true),
  ('Pediatric Homeopathy', 'শিশু হোমিওপ্যাথি', 'homeopathic', 'baby', 'Gentle care for children', true),
  ('Skin & Allergy', 'চর্ম ও অ্যালার্জি', 'homeopathic', 'sparkles', 'Eczema, allergy and hair', true),
  ('Women''s Health', 'নারী স্বাস্থ্য', 'homeopathic', 'heart', 'Hormonal and cycle care', true)
on conflict (name, medicine_type) do update set
  name_bn = excluded.name_bn, icon = excluded.icon, description = excluded.description,
  is_active = true, updated_at = now();

-- ======== seed_02_doctors.sql ========
-- MediNova Module 2 seed (part 2/2): 12 doctors, postings, schedules, services.
-- Run AFTER seed_01_catalog.sql. Idempotent via slug / posting unique keys.

-- 8 allopathic doctors -------------------------------------------------------
insert into public.doctors (slug, department_id, medicine_type, full_name, full_name_bn, bio, qualifications, specialties, experience_years, registration_no, photo_url, languages, telemedicine_enabled, is_active)
select x.slug, d.id, 'allopathic'::medicine_type, x.full_name, x.full_name_bn, x.bio,
       x.qualifications::text[], x.specialties::text[], x.exp, x.reg, x.photo, '{English,Bangla}'::text[], x.tele, true
from (values
  ('tanvir-ahmed', 'Medicine', 'Dr. Tanvir Ahmed', 'ডা. তানভীর আহমেদ', 'Internal medicine, diabetes and hypertension (Dhaka Medical College).', '{MBBS,MD (Internal Medicine)}', '{Diabetes,Hypertension,Thyroid}', 12, 'BMDC A-51234', 'https://placehold.co/400x400?text=TA', true),
  ('nusrat-jahan', 'Cardiology', 'Dr. Nusrat Jahan', 'ডা. নুসরাত জাহান', 'Interventional cardiologist, echocardiography.', '{MBBS,D-Card}', '{Chest Pain,ECG,Echo}', 10, 'BMDC A-52310', 'https://placehold.co/400x400?text=NJ', true),
  ('farhana-akter', 'Gynecology', 'Dr. Farhana Akter', 'ডা. ফারহানা আক্তার', 'High-risk pregnancy and infertility counselling.', '{MBBS,MS (Obs & Gynae)}', '{Pregnancy,PCOS,Infertility}', 11, 'BMDC A-50987', 'https://placehold.co/400x400?text=FA', true),
  ('rakib-hasan', 'Pediatrics', 'Dr. Rakib Hasan', 'ডা. রাকিব হাসান', 'Newborn and child nutrition specialist.', '{MBBS,DCH}', '{Newborn,Vaccination,Nutrition}', 9, 'BMDC A-54112', 'https://placehold.co/400x400?text=RH', false),
  ('mahmudul-karim', 'Orthopedics', 'Dr. Mahmudul Karim', 'ডা. মাহমুদুল করিম', 'Fracture, arthritis and sports injury.', '{MBBS,MS (Ortho)}', '{Fracture,Back Pain,Knee}', 13, 'BMDC A-49876', 'https://placehold.co/400x400?text=MK', false),
  ('sharmin-sultana', 'ENT', 'Dr. Sharmin Sultana', 'ডা. শারমিন সুলতানা', 'Tonsil, sinus and hearing problems.', '{MBBS,DLO}', '{Sinus,Tonsil,Hearing}', 8, 'BMDC A-55621', 'https://placehold.co/400x400?text=SS', true),
  ('imran-chowdhury', 'Dermatology', 'Dr. Imran Chowdhury', 'ডা. ইমরান চৌধুরী', 'Acne, eczema and hair fall treatment.', '{MBBS,DDV}', '{Acne,Eczema,Hair}', 7, 'BMDC A-56100', 'https://placehold.co/400x400?text=IC', true),
  ('anjuman-ara', 'Neurology', 'Dr. Anjuman Ara', 'ডা. আনজুমান আরা', 'Migraine, stroke and epilepsy care.', '{MBBS,MD (Neurology)}', '{Migraine,Stroke,Epilepsy}', 12, 'BMDC A-50333', 'https://placehold.co/400x400?text=AA', true)
) as x(slug, dept, full_name, full_name_bn, bio, qualifications, specialties, exp, reg, photo, tele)
join public.departments d on d.name = x.dept and d.medicine_type = 'allopathic'
on conflict (slug) do update set
  department_id = excluded.department_id, full_name = excluded.full_name,
  full_name_bn = excluded.full_name_bn, bio = excluded.bio,
  qualifications = excluded.qualifications, specialties = excluded.specialties,
  experience_years = excluded.experience_years, telemedicine_enabled = excluded.telemedicine_enabled,
  is_active = true, updated_at = now();

-- 4 homeopathic doctors -------------------------------------------------------
insert into public.doctors (slug, department_id, medicine_type, full_name, full_name_bn, bio, qualifications, specialties, experience_years, registration_no, photo_url, languages, telemedicine_enabled, is_active)
select x.slug, d.id, 'homeopathic'::medicine_type, x.full_name, x.full_name_bn, x.bio,
       x.qualifications::text[], x.specialties::text[], x.exp, x.reg, x.photo, '{English,Bangla}'::text[], true, true
from (values
  ('kamrul-islam', 'General Homeopathy', 'Dr. Kamrul Islam (Homeo)', 'ডা. কামরুল ইসলাম (হোমিও)', 'Classical homeopathy for acute and chronic illness.', '{DHMS,BHMS}', '{Gastric,Cold,Weakness}', 14, 'BHMC H-10231', 'https://placehold.co/400x400?text=KI'),
  ('salma-begum', 'Chronic Disease', 'Dr. Salma Begum (Homeo)', 'ডা. সালমা বেগম (হোমিও)', 'Arthritis, piles and chronic skin cases.', '{BHMS}', '{Arthritis,Piles,Migraine}', 10, 'BHMC H-11002', 'https://placehold.co/400x400?text=SB'),
  ('habib-ullah', 'Pediatric Homeopathy', 'Dr. Habib Ullah (Homeo)', 'ডা. হাবিব উল্লাহ (হোমিও)', 'Teething, colic and recurrent cold in children.', '{DHMS}', '{Colic,Teething,Cold}', 9, 'BHMC H-11455', 'https://placehold.co/400x400?text=HU'),
  ('marium-khan', 'Women''s Health', 'Dr. Marium Khan (Homeo)', 'ডা. মারিয়াম খান (হোমিও)', 'PCOS, irregular cycle and anemia support.', '{BHMS}', '{PCOS,Anemia,Leucorrhoea}', 8, 'BHMC H-11890', 'https://placehold.co/400x400?text=MKH')
) as x(slug, dept, full_name, full_name_bn, bio, qualifications, specialties, exp, reg, photo)
join public.departments d on d.name = x.dept and d.medicine_type = 'homeopathic'
on conflict (slug) do update set
  department_id = excluded.department_id, full_name = excluded.full_name,
  full_name_bn = excluded.full_name_bn, bio = excluded.bio,
  qualifications = excluded.qualifications, specialties = excluded.specialties,
  experience_years = excluded.experience_years, telemedicine_enabled = true,
  is_active = true, updated_at = now();

-- ======== seed_03_postings.sql ========
-- MediNova Module 2 seed (part 3/3): postings with per-branch fees, schedules, services.
-- Fees in BDT: 500-1500, different per branch. Run AFTER seed_02_doctors.sql.

-- Postings: every doctor practises at Uttara + Dhanmondi; leads also at GEC.
insert into public.doctor_branches (doctor_id, branch_id, consultation_fee, followup_fee, followup_valid_days, telemedicine_fee, room_no)
select d.id, b.id, f.fee, f.follow, 14, f.tele, f.room
from public.doctors d
join (values
  ('tanvir-ahmed', 'uttara', 1000, 600, 800, '304'),
  ('tanvir-ahmed', 'dhanmondi', 1200, 700, 900, '205'),
  ('tanvir-ahmed', 'gec-chattogram', 800, 500, 700, '101'),
  ('nusrat-jahan', 'uttara', 1200, 700, 1000, '305'),
  ('nusrat-jahan', 'dhanmondi', 1500, 800, 1200, '206'),
  ('farhana-akter', 'uttara', 1000, 600, 800, '306'),
  ('farhana-akter', 'dhanmondi', 1200, 700, 900, '207'),
  ('rakib-hasan', 'uttara', 800, 500, null, '307'),
  ('rakib-hasan', 'dhanmondi', 1000, 600, null, '208'),
  ('mahmudul-karim', 'uttara', 1200, 700, null, '308'),
  ('mahmudul-karim', 'gec-chattogram', 1000, 600, null, '102'),
  ('sharmin-sultana', 'dhanmondi', 800, 500, 600, '209'),
  ('sharmin-sultana', 'uttara', 700, 400, 500, '309'),
  ('imran-chowdhury', 'uttara', 800, 500, 600, '310'),
  ('imran-chowdhury', 'dhanmondi', 1000, 600, 700, '210'),
  ('anjuman-ara', 'dhanmondi', 1200, 700, 1000, '211'),
  ('anjuman-ara', 'uttara', 1000, 600, 800, '311'),
  ('kamrul-islam', 'uttara', 600, 400, 500, 'H-01'),
  ('kamrul-islam', 'dhanmondi', 700, 400, 500, 'H-02'),
  ('kamrul-islam', 'gec-chattogram', 500, 300, 400, 'H-01'),
  ('salma-begum', 'uttara', 600, 350, 500, 'H-02'),
  ('salma-begum', 'dhanmondi', 700, 400, 500, 'H-03'),
  ('habib-ullah', 'dhanmondi', 500, 300, 400, 'H-04'),
  ('habib-ullah', 'uttara', 500, 300, 400, 'H-03'),
  ('marium-khan', 'uttara', 600, 350, 500, 'H-04'),
  ('marium-khan', 'gec-chattogram', 500, 300, 400, 'H-02')
) as f(slug, branch, fee, follow, tele, room)
  on d.slug = f.slug
join public.branches b on b.slug = f.branch
on conflict (doctor_id, branch_id) do update set
  consultation_fee = excluded.consultation_fee, followup_fee = excluded.followup_fee,
  telemedicine_fee = excluded.telemedicine_fee, room_no = excluded.room_no,
  updated_at = now();

-- Schedules: Sat-Thu (weekday 6,0-4) morning 10:00-13:00 + evening 17:00-21:00.
-- weekday: 0=Sunday .. 6=Saturday (Postgres extract(dow)).
insert into public.doctor_schedules (doctor_branch_id, weekday, start_time, end_time, slot_minutes, max_per_slot, is_active)
select db.id, w.wd, w.s, w.e, 15, 1, true
from public.doctor_branches db
cross join (values
  (6, '10:00'::time, '13:00'::time), (6, '17:00'::time, '21:00'::time),
  (0, '10:00'::time, '13:00'::time), (0, '17:00'::time, '21:00'::time),
  (1, '10:00'::time, '13:00'::time), (1, '17:00'::time, '21:00'::time),
  (2, '10:00'::time, '13:00'::time), (2, '17:00'::time, '21:00'::time),
  (3, '10:00'::time, '13:00'::time), (3, '17:00'::time, '21:00'::time),
  (4, '10:00'::time, '13:00'::time), (4, '17:00'::time, '21:00'::time)
) as w(wd, s, e)
on conflict do nothing;

-- 6 services per branch (lab + imaging + packages/ambulance mix).
insert into public.services (branch_id, name, name_bn, category, price, description)
select b.id, s.name, s.name_bn, s.cat::text, s.price, s.descr
from public.branches b
cross join (values
  ('CBC Blood Test', 'সিবিসি রক্ত পরীক্ষা', 'lab', 400, 'Complete blood count with ESR'),
  ('HbA1c (Diabetes)', 'এইচবিএ১সি (ডায়াবেটিস)', 'lab', 900, '3-month sugar average'),
  ('ECG', 'ইসিজি', 'imaging', 500, '12-lead ECG with report'),
  ('Ultrasonography', 'আল্ট্রাসনোগ্রাম', 'imaging', 1200, 'Whole abdomen USG'),
  ('Executive Health Package', 'এক্সিকিউটিভ হেলথ প্যাকেজ', 'package', 4500, 'CBC, lipid, liver, kidney, ECG + consult'),
  ('Ambulance (City)', 'অ্যাম্বুলেন্স (শহর)', 'ambulance', 1500, 'AC ambulance inside city, oxygen support')
) as s(name, name_bn, cat, price, descr)
on conflict do nothing;

