-- MediNova bootstrap part 1 of 3.
-- Run parts 1, 2, 3 IN ORDER in the Supabase SQL Editor. Run each part exactly once.
-- Generated by scripts/build-bootstrap.mjs - do not edit by hand.

-- ======== 0001_foundation.sql ========
-- MediNova Module 2: full database schema (part 1/2 - enums + core tables).
-- Applies cleanly on a fresh DB. Run with: supabase db push

create extension if not exists "pgcrypto";

do $$ begin
  create type medicine_type as enum ('allopathic', 'homeopathic');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type user_role as enum ('patient', 'doctor', 'receptionist', 'branch_admin', 'super_admin');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type appt_status as enum ('pending', 'confirmed', 'checked_in', 'in_consultation', 'completed', 'cancelled', 'no_show');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type visit_type as enum ('new', 'followup', 'telemedicine');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type pay_status as enum ('unpaid', 'pay_at_counter', 'paid', 'refunded', 'failed');
exception when duplicate_object then null;
end $$;

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_bn text not null,
  slug text unique not null,
  address text not null,
  address_bn text not null,
  city text not null,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  phone text not null,
  emergency_phone text not null,
  email text,
  opening_hours jsonb not null default '{}'::jsonb,
  facilities text[] not null default '{}',
  photo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role user_role not null default 'patient',
  branch_id uuid references public.branches(id) on delete set null,
  avatar_url text,
  preferred_lang text not null default 'en' check (preferred_lang in ('en', 'bn')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.departments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  name_bn text not null,
  medicine_type medicine_type not null,
  icon text,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name, medicine_type)
);

create table public.doctors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid references public.profiles(id) on delete set null,
  department_id uuid references public.departments(id) on delete set null,
  medicine_type medicine_type not null,
  full_name text not null,
  full_name_bn text not null,
  slug text unique not null,
  bio text,
  qualifications text[] not null default '{}',
  specialties text[] not null default '{}',
  experience_years int not null default 0 check (experience_years >= 0),
  registration_no text,
  photo_url text,
  languages text[] not null default '{English,Bangla}',
  rating_avg numeric(3, 2) not null default 0 check (rating_avg >= 0 and rating_avg <= 5),
  rating_count int not null default 0 check (rating_count >= 0),
  telemedicine_enabled boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.doctor_branches (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  branch_id uuid not null references public.branches(id) on delete cascade,
  consultation_fee numeric(10, 2) not null check (consultation_fee >= 0),
  followup_fee numeric(10, 2) not null check (followup_fee >= 0),
  followup_valid_days int not null default 14 check (followup_valid_days >= 0),
  telemedicine_fee numeric(10, 2) check (telemedicine_fee is null or telemedicine_fee >= 0),
  room_no text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doctor_id, branch_id)
);

create table public.doctor_schedules (
  id uuid primary key default gen_random_uuid(),
  doctor_branch_id uuid not null references public.doctor_branches(id) on delete cascade,
  weekday smallint not null check (weekday between 0 and 6),
  start_time time not null,
  end_time time not null,
  slot_minutes int not null default 15 check (slot_minutes > 0 and slot_minutes <= 480),
  max_per_slot int not null default 1 check (max_per_slot > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (doctor_branch_id, weekday, start_time, end_time),
  check (start_time < end_time)
);

create table public.doctor_time_off (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  branch_id uuid references public.branches(id) on delete cascade,
  start_at timestamptz not null,
  end_at timestamptz not null,
  reason text,
  created_at timestamptz not null default now(),
  check (start_at < end_at)
);

create table public.patients (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  full_name text not null,
  dob date,
  gender text check (gender is null or gender in ('male', 'female', 'other')),
  phone text,
  blood_group text,
  address text,
  allergies text,
  chronic_conditions text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ======== 0002_clinical.sql ========
-- MediNova Module 2: appointments, payments, clinical, engagement (part 2/2).
-- Depends on 0001_foundation.sql.

create table public.appointments (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  patient_id uuid not null references public.patients(id) on delete restrict,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  branch_id uuid not null references public.branches(id) on delete restrict,
  doctor_branch_id uuid not null references public.doctor_branches(id) on delete restrict,
  appt_date date not null,
  slot_start time not null,
  slot_end time not null,
  visit_type visit_type not null,
  status appt_status not null default 'pending',
  fee numeric(10, 2) not null check (fee >= 0),
  payment_status pay_status not null default 'unpaid',
  payment_method text,
  symptoms text,
  ai_triage jsonb,
  queue_no int,
  checked_in_at timestamptz,
  cancelled_reason text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (slot_start < slot_end)
);

create unique index appointments_no_double_book_idx
  on public.appointments (doctor_branch_id, appt_date, slot_start)
  where status not in ('cancelled', 'no_show');

create index appointments_lookup_idx on public.appointments (doctor_id, branch_id, appt_date, status);
create index appointments_patient_idx on public.appointments (patient_id, appt_date desc);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  amount numeric(10, 2) not null check (amount >= 0),
  method text not null check (method in ('cash', 'bkash', 'nagad', 'card')),
  provider_ref text,
  status pay_status not null default 'unpaid',
  paid_at timestamptz,
  raw jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.prescriptions (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  doctor_id uuid not null references public.doctors(id) on delete restrict,
  patient_id uuid not null references public.patients(id) on delete restrict,
  diagnosis text,
  medicines jsonb not null default '[]'::jsonb,
  advice text,
  next_visit_date date,
  pdf_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.medical_records (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references public.patients(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  title text not null,
  type text not null check (type in ('lab', 'xray', 'report')),
  file_path text not null,
  created_at timestamptz not null default now()
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid unique not null references public.appointments(id) on delete cascade,
  doctor_id uuid not null references public.doctors(id) on delete cascade,
  patient_id uuid not null references public.patients(id) on delete cascade,
  rating smallint not null check (rating between 1 and 5),
  comment text,
  is_approved boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  channel text not null check (channel in ('email', 'sms', 'push', 'inapp')),
  title text not null,
  body text,
  read_at timestamptz,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.services (
  id uuid primary key default gen_random_uuid(),
  branch_id uuid not null references public.branches(id) on delete cascade,
  name text not null,
  name_bn text not null,
  category text not null check (category in ('lab', 'imaging', 'package', 'ambulance')),
  price numeric(10, 2) not null check (price >= 0),
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (branch_id, name)
);

create table public.announcements (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text,
  branch_id uuid references public.branches(id) on delete cascade,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (starts_at is null or ends_at is null or starts_at <= ends_at)
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id text,
  meta jsonb,
  created_at timestamptz not null default now()
);

-- ======== 0003_functions.sql ========
-- MediNova Module 2: booking engine (part 1 - helpers + slot generation).
-- Timezone: Asia/Dhaka everywhere user-facing.

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_branches_updated on public.branches;
create trigger trg_branches_updated before update on public.branches
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_profiles_updated on public.profiles;
create trigger trg_profiles_updated before update on public.profiles
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_departments_updated on public.departments;
create trigger trg_departments_updated before update on public.departments
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_doctors_updated on public.doctors;
create trigger trg_doctors_updated before update on public.doctors
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_doctor_branches_updated on public.doctor_branches;
create trigger trg_doctor_branches_updated before update on public.doctor_branches
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_doctor_schedules_updated on public.doctor_schedules;
create trigger trg_doctor_schedules_updated before update on public.doctor_schedules
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_patients_updated on public.patients;
create trigger trg_patients_updated before update on public.patients
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_appointments_updated on public.appointments;
create trigger trg_appointments_updated before update on public.appointments
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_payments_updated on public.payments;
create trigger trg_payments_updated before update on public.payments
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_prescriptions_updated on public.prescriptions;
create trigger trg_prescriptions_updated before update on public.prescriptions
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_reviews_updated on public.reviews;
create trigger trg_reviews_updated before update on public.reviews
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_services_updated on public.services;
create trigger trg_services_updated before update on public.services
  for each row execute function public.touch_updated_at();

drop trigger if exists trg_announcements_updated on public.announcements;
create trigger trg_announcements_updated before update on public.announcements
  for each row execute function public.touch_updated_at();

-- Auto-create a patient-role profile when a new auth user signs up.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role, preferred_lang)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    'patient',
    coalesce(new.raw_user_meta_data ->> 'preferred_lang', 'en')
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Next queue number for a posting+date (1-based, counts active bookings).
create or replace function public.next_queue_number(
  p_doctor_branch_id uuid,
  p_date date
)
returns int language plpgsql stable as $$
declare
  v_count int;
begin
  select count(*)::int into v_count
  from public.appointments a
  where a.doctor_branch_id = p_doctor_branch_id
    and a.appt_date = p_date
    and a.status not in ('cancelled', 'no_show');
  return coalesce(v_count, 0) + 1;
end $$;

-- ======== 0004_booking.sql ========
-- MediNova Module 2: slot generation + atomic booking (part 2).
-- get_available_slots: expand weekly schedule rows for the weekday into
-- time slots, subtract overlapping time-off and active bookings, and hide
-- past times when p_date is today in Asia/Dhaka.

create or replace function public.get_available_slots(
  p_doctor_branch_id uuid,
  p_date date
)
returns table (slot_start time, slot_end time, is_available boolean)
language plpgsql stable security definer set search_path = public as $$
declare
  v_weekday int := extract(dow from p_date)::int;
  v_today date := (now() at time zone 'Asia/Dhaka')::date;
  v_now time := (now() at time zone 'Asia/Dhaka')::time;
  r record;
  v_cursor time;
  v_end time;
  v_off boolean;
  v_booked int;
begin
  for r in
    select s.start_time, s.end_time, s.slot_minutes, s.max_per_slot
    from public.doctor_schedules s
    join public.doctor_branches db on db.id = s.doctor_branch_id
    join public.doctors d on d.id = db.doctor_id
    where s.doctor_branch_id = p_doctor_branch_id
      and s.weekday = v_weekday
      and s.is_active = true
      and db.doctor_id is not null
      and d.is_active = true
    order by s.start_time
  loop
    v_cursor := r.start_time;
    while v_cursor < r.end_time loop
      v_end := (v_cursor + (r.slot_minutes || ' minutes')::interval)::time;
      if v_end > r.end_time then
        v_end := r.end_time;
      end if;

      -- Time-off overlap (branch-scoped or doctor-wide), compared in Dhaka wall time.
      select exists (
        select 1 from public.doctor_time_off t
        join public.doctor_branches db2 on db2.id = p_doctor_branch_id
        where t.doctor_id = db2.doctor_id
          and (t.branch_id is null or t.branch_id = db2.branch_id)
          and tstzrange(t.start_at, t.end_at, '[)') @> ((p_date + v_cursor) at time zone 'Asia/Dhaka')
      ) into v_off;

      -- Active bookings overlapping this slot start.
      select count(*)::int into v_booked
      from public.appointments a
      where a.doctor_branch_id = p_doctor_branch_id
        and a.appt_date = p_date
        and a.slot_start = v_cursor
        and a.status not in ('cancelled', 'no_show');

      slot_start := v_cursor;
      slot_end := v_end;
      is_available := (not v_off)
        and (v_booked < r.max_per_slot)
        and not (p_date = v_today and v_cursor <= v_now);
      return next;

      v_cursor := v_end;
      exit when v_cursor >= r.end_time;
    end loop;
  end loop;
  return;
end $$;

-- book_appointment: atomic single-slot booking with fee resolution.
-- Raises 'SLOT_TAKEN' (SQLSTATE P0001) when the slot is unavailable.
create or replace function public.book_appointment(
  p_patient_id uuid,
  p_doctor_branch_id uuid,
  p_date date,
  p_slot_start time,
  p_visit_type visit_type,
  p_symptoms text default null,
  p_created_by uuid default null
)
returns public.appointments
language plpgsql security definer set search_path = public as $$
declare
  v_db public.doctor_branches%rowtype;
  v_doc public.doctors%rowtype;
  v_slot record;
  v_fee numeric(10, 2);
  v_queue int;
  v_code text;
  v_seq int;
  v_last_completed date;
  v_row public.appointments%rowtype;
begin
  select * into v_db from public.doctor_branches where id = p_doctor_branch_id for update;
  if not found then
    raise exception 'DOCTOR_BRANCH_NOT_FOUND';
  end if;
  select * into v_doc from public.doctors where id = v_db.doctor_id;
  if not found or v_doc.is_active = false then
    raise exception 'DOCTOR_INACTIVE';
  end if;

  if p_visit_type = 'telemedicine' and v_doc.telemedicine_enabled = false and v_db.telemedicine_fee is null then
    raise exception 'TELEMEDICINE_DISABLED';
  end if;

  -- Availability check inside the row lock on doctor_branches.
  select s.slot_start, s.slot_end, s.is_available into v_slot
  from public.get_available_slots(p_doctor_branch_id, p_date) s
  where s.slot_start = p_slot_start;
  if not found or v_slot.is_available = false then
    raise exception 'SLOT_TAKEN';
  end if;

  -- Fee: followup price applies only when the same patient saw the same
  -- doctor within followup_valid_days (completed or active history).
  if p_visit_type = 'telemedicine' then
    v_fee := coalesce(v_db.telemedicine_fee, v_db.consultation_fee);
  elsif p_visit_type = 'followup' then
    select max(a.appt_date) into v_last_completed
    from public.appointments a
    where a.patient_id = p_patient_id
      and a.doctor_id = v_db.doctor_id
      and a.status not in ('cancelled', 'no_show');
    if v_last_completed is not null and (p_date - v_last_completed) <= v_db.followup_valid_days then
      v_fee := v_db.followup_fee;
    else
      v_fee := v_db.consultation_fee;
    end if;
  else
    v_fee := v_db.consultation_fee;
  end if;

  v_queue := public.next_queue_number(p_doctor_branch_id, p_date);

  select count(*)::int + 1 into v_seq
  from public.appointments
  where appt_date = p_date;
  v_code := 'MN-' || to_char(p_date, 'YYMMDD') || '-' || lpad(v_seq::text, 4, '0');

  begin
    insert into public.appointments (
      code, patient_id, doctor_id, branch_id, doctor_branch_id,
      appt_date, slot_start, slot_end, visit_type, status,
      fee, payment_status, symptoms, queue_no, created_by
    ) values (
      v_code, p_patient_id, v_db.doctor_id, v_db.branch_id, p_doctor_branch_id,
      p_date, v_slot.slot_start, v_slot.slot_end, p_visit_type, 'pending',
      v_fee, 'unpaid', p_symptoms, v_queue, p_created_by
    )
    returning * into v_row;
  exception when unique_violation then
    raise exception 'SLOT_TAKEN';
  end;

  return v_row;
end $$;

-- ======== 0005_rls.sql ========
-- MediNova Module 2: Row Level Security (part 3/3 of migrations).
-- Catalog is publicly readable; clinical + PII tables are locked down.
-- Writes go through service-role / SECURITY DEFINER functions.

-- Enable RLS on every public table ------------------------------------------
alter table public.branches enable row level security;
alter table public.profiles enable row level security;
alter table public.departments enable row level security;
alter table public.doctors enable row level security;
alter table public.doctor_branches enable row level security;
alter table public.doctor_schedules enable row level security;
alter table public.doctor_time_off enable row level security;
alter table public.patients enable row level security;
alter table public.appointments enable row level security;
alter table public.payments enable row level security;
alter table public.prescriptions enable row level security;
alter table public.medical_records enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;
alter table public.services enable row level security;
alter table public.announcements enable row level security;
alter table public.audit_logs enable row level security;

-- Helper: current user's role --------------------------------------------------
create or replace function public.current_role()
returns user_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

-- Public catalog reads ----------------------------------------------------------
create policy "public read active branches" on public.branches
  for select using (is_active = true);

create policy "public read active departments" on public.departments
  for select using (is_active = true);

create policy "public read active doctors" on public.doctors
  for select using (is_active = true);

create policy "public read doctor postings" on public.doctor_branches
  for select using (true);

create policy "public read active schedules" on public.doctor_schedules
  for select using (is_active = true);

create policy "public read approved reviews" on public.reviews
  for select using (is_approved = true);

create policy "public read branch services" on public.services
  for select using (true);

create policy "public read live announcements" on public.announcements
  for select using (
    (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now())
  );

-- Authenticated users --------------------------------------------------------------
-- Patients own their family profiles; staff (any non-patient role) can read all.
create policy "patients owner read" on public.patients
  for select using (auth.uid() = owner_id or public.current_role() <> 'patient');

create policy "patients owner insert" on public.patients
  for insert with check (auth.uid() = owner_id);

create policy "patients owner update" on public.patients
  for update using (auth.uid() = owner_id);

-- Appointments: owners of the patient record + staff can read; booking happens
-- through book_appointment() (SECURITY DEFINER) so no direct insert policy here.
create policy "appointments read own or staff" on public.appointments
  for select using (
    exists (select 1 from public.patients p where p.id = patient_id and p.owner_id = auth.uid())
    or public.current_role() <> 'patient'
  );

-- Users read their own profile; anyone with a staff role reads all profiles.
create policy "profiles self read" on public.profiles
  for select using (id = auth.uid() or public.current_role() <> 'patient');

create policy "profiles self update" on public.profiles
  for update using (id = auth.uid());

-- Staff-only tables: no INSERT/UPDATE/DELETE policies for anon/authenticated
-- except explicit below; service_role bypasses RLS for server writes.
-- Notifications: recipient reads own; recipient marks read.
create policy "notifications own read" on public.notifications
  for select using (user_id = auth.uid());

create policy "notifications own mark read" on public.notifications
  for update using (user_id = auth.uid());

-- Payments / prescriptions / records visible to the owning patient + staff.
create policy "payments via appointment" on public.payments
  for select using (
    exists (
      select 1 from public.appointments a
      join public.patients p on p.id = a.patient_id
      where a.id = appointment_id and (p.owner_id = auth.uid() or public.current_role() <> 'patient')
    )
  );

create policy "prescriptions via patient" on public.prescriptions
  for select using (
    exists (
      select 1 from public.patients p
      where p.id = patient_id and (p.owner_id = auth.uid() or public.current_role() <> 'patient')
    )
  );

create policy "records via patient" on public.medical_records
  for select using (
    exists (
      select 1 from public.patients p
      where p.id = patient_id and (p.owner_id = auth.uid() or public.current_role() <> 'patient')
    )
  );

create policy "reviews own insert" on public.reviews
  for insert with check (
    exists (select 1 from public.patients p where p.id = patient_id and p.owner_id = auth.uid())
  );

-- ======== 0006_auth_helpers.sql ========
-- MediNova Module 3: policy reset + RLS helper functions.
-- Drops every Module 2 stub policy (idempotent), then recreates the helpers
-- used by 0007_rls_policies.sql. All helpers are SECURITY DEFINER so policy
-- subqueries never re-enter RLS (no policy recursion) and evaluate cheaply.

-- Drop all existing policies in public ------------------------------------------
do $$
declare r record;
begin
  for r in select policyname, tablename from pg_policies where schemaname = 'public' loop
    execute format('drop policy %I on public.%I', r.policyname, r.tablename);
  end loop;
end $$;

-- Role / branch helpers ----------------------------------------------------------
create or replace function public.current_role()
returns user_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.current_branch_id()
returns uuid language sql stable security definer set search_path = public as $$
  select branch_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select public.current_role() in ('receptionist', 'branch_admin', 'super_admin');
$$;

create or replace function public.is_branch_staff()
returns boolean language sql stable security definer set search_path = public as $$
  select public.current_role() in ('receptionist', 'branch_admin');
$$;

-- Old-value readers for WITH CHECK clauses (a policy cannot see the pre-update row).
create or replace function public.profile_role_of(p_id uuid)
returns user_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = p_id;
$$;

create or replace function public.profile_branch_of(p_id uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select branch_id from public.profiles where id = p_id;
$$;

-- Ownership predicates ------------------------------------------------------------
create or replace function public.is_patient_owner(p_patient_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.patients where id = p_patient_id and owner_id = auth.uid());
$$;

create or replace function public.is_appointment_owner(p_appointment_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments a
    join public.patients p on p.id = a.patient_id
    where a.id = p_appointment_id and p.owner_id = auth.uid()
  );
$$;

create or replace function public.is_appointment_doctor(p_appointment_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments a
    join public.doctors d on d.id = a.doctor_id
    where a.id = p_appointment_id and d.profile_id = auth.uid()
  );
$$;

create or replace function public.is_patient_assigned_doctor(p_patient_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments a
    join public.doctors d on d.id = a.doctor_id
    where a.patient_id = p_patient_id and d.profile_id = auth.uid()
  );
$$;

create or replace function public.is_my_doctor(p_doctor_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.doctors where id = p_doctor_id and profile_id = auth.uid());
$$;

create or replace function public.is_my_posting(p_doctor_branch_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.doctor_branches db
    join public.doctors d on d.id = db.doctor_id
    where db.id = p_doctor_branch_id and d.profile_id = auth.uid()
  );
$$;

-- Branch predicates ----------------------------------------------------------------
create or replace function public.posting_at_my_branch(p_doctor_branch_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.doctor_branches
    where id = p_doctor_branch_id and branch_id = public.current_branch_id()
  );
$$;

create or replace function public.doctor_posts_at(p_doctor_id uuid, p_branch_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.doctor_branches
    where doctor_id = p_doctor_id and branch_id = p_branch_id
  );
$$;

create or replace function public.is_appointment_at_my_branch(p_appointment_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments
    where id = p_appointment_id and branch_id = public.current_branch_id()
  );
$$;

create or replace function public.patient_at_my_branch(p_patient_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments
    where patient_id = p_patient_id and branch_id = public.current_branch_id()
  );
$$;

create or replace function public.doctor_at_my_branch(p_doctor_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.doctor_branches
    where doctor_id = p_doctor_id and branch_id = public.current_branch_id()
  );
$$;

-- Clinical integrity predicates ------------------------------------------------------
create or replace function public.doctor_owns_prescription(p_appointment_id uuid, p_doctor_id uuid, p_patient_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments a
    join public.doctors d on d.id = a.doctor_id
    where a.id = p_appointment_id
      and a.doctor_id = p_doctor_id
      and a.patient_id = p_patient_id
      and d.profile_id = auth.uid()
  );
$$;

create or replace function public.appointment_belongs_to_patient(p_appointment_id uuid, p_patient_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.appointments
    where id = p_appointment_id and patient_id = p_patient_id
  );
$$;

-- Private storage predicate: records/prescriptions buckets are patient-foldered.
-- p_folder is the first path segment as TEXT so malformed names deny cleanly
-- instead of raising a uuid cast error inside the policy.
create or replace function public.storage_patient_access(p_folder text)
returns boolean language sql stable security definer set search_path = public as $$
  select
    exists (
      select 1 from public.patients p
      where p.id::text = p_folder and p.owner_id = auth.uid()
    )
    or exists (
      select 1 from public.appointments a
      join public.doctors d on d.id = a.doctor_id
      where a.patient_id::text = p_folder and d.profile_id = auth.uid()
    )
    or (
      public.is_branch_staff()
      and exists (
        select 1 from public.appointments a
        where a.patient_id::text = p_folder
          and a.branch_id = public.current_branch_id()
      )
    );
$$;

