-- MediNova bootstrap part 2 of 3.
-- Run parts 1, 2, 3 IN ORDER in the Supabase SQL Editor. Run each part exactly once.
-- Generated by scripts/build-bootstrap.mjs - do not edit by hand.

-- ======== 0007_rls_policies.sql ========
-- MediNova Module 3: complete table policies (runs after 0006_auth_helpers.sql).
-- Matrix: public catalog reads; patients own their rows; doctors get their
-- assigned appointments + prescriptions; receptionist/branch_admin are scoped
-- to current_branch_id(); super_admin gets a uniform FOR ALL policy (part 2);
-- storage bucket policies follow in part 2 as well.

-- branches --------------------------------------------------------------------------
create policy "branches public read active" on public.branches
  for select using (is_active = true);

create policy "branches staff read own" on public.branches
  for select using (public.is_branch_staff() and id = public.current_branch_id());

create policy "branches admin update" on public.branches
  for update
  using (public.current_role() = 'branch_admin' and id = public.current_branch_id())
  with check (public.current_role() = 'branch_admin' and id = public.current_branch_id());

-- profiles --------------------------------------------------------------------------
create policy "profiles self read" on public.profiles
  for select using (id = auth.uid() or public.is_staff());

create policy "profiles self update" on public.profiles
  for update
  using (id = auth.uid())
  with check (
    id = auth.uid()
    and role = public.current_role()
    and branch_id is not distinct from public.current_branch_id()
  );

create policy "profiles branch staff update" on public.profiles
  for update
  using (public.is_branch_staff())
  with check (
    public.is_branch_staff()
    and role = public.profile_role_of(id)
    and branch_id is not distinct from public.profile_branch_of(id)
  );

-- departments ------------------------------------------------------------------------
create policy "departments public read" on public.departments
  for select using (is_active = true or public.is_staff());

-- doctors ---------------------------------------------------------------------------
create policy "doctors public read" on public.doctors
  for select using (is_active = true or public.is_staff());

create policy "doctors self update" on public.doctors
  for update using (profile_id = auth.uid()) with check (profile_id = auth.uid());

-- doctor_branches -------------------------------------------------------------------
create policy "postings public read" on public.doctor_branches for select using (true);

create policy "postings branch staff insert" on public.doctor_branches
  for insert with check (public.is_branch_staff() and branch_id = public.current_branch_id());

create policy "postings branch staff update" on public.doctor_branches
  for update
  using (public.is_branch_staff() and branch_id = public.current_branch_id())
  with check (public.is_branch_staff() and branch_id = public.current_branch_id());

-- doctor_schedules ------------------------------------------------------------------
create policy "schedules public read" on public.doctor_schedules
  for select using (is_active = true or public.is_staff());

create policy "schedules doctor write" on public.doctor_schedules
  for all
  using (public.is_my_posting(doctor_branch_id))
  with check (public.is_my_posting(doctor_branch_id));

create policy "schedules branch staff write" on public.doctor_schedules
  for all
  using (public.is_branch_staff() and public.posting_at_my_branch(doctor_branch_id))
  with check (public.is_branch_staff() and public.posting_at_my_branch(doctor_branch_id));

-- doctor_time_off -------------------------------------------------------------------
create policy "time off related read" on public.doctor_time_off
  for select using (
    public.is_my_doctor(doctor_id)
    or (public.is_branch_staff() and (branch_id is null or branch_id = public.current_branch_id()))
  );

create policy "time off doctor write" on public.doctor_time_off
  for all
  using (public.is_my_doctor(doctor_id))
  with check (
    public.is_my_doctor(doctor_id)
    and (branch_id is null or public.doctor_posts_at(doctor_id, branch_id))
  );

create policy "time off branch staff write" on public.doctor_time_off
  for all
  using (public.is_branch_staff() and branch_id = public.current_branch_id())
  with check (public.is_branch_staff() and branch_id = public.current_branch_id());

-- patients --------------------------------------------------------------------------
create policy "patients owner read" on public.patients
  for select using (owner_id = auth.uid());

create policy "patients assigned doctor read" on public.patients
  for select using (public.is_patient_assigned_doctor(id));

create policy "patients staff read" on public.patients
  for select using (public.is_staff() and public.patient_at_my_branch(id));

create policy "patients owner insert" on public.patients
  for insert with check (owner_id = auth.uid());

create policy "patients owner update" on public.patients
  for update
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy "patients owner delete" on public.patients
  for delete using (owner_id = auth.uid());

create policy "patients staff insert" on public.patients
  for insert with check (public.is_branch_staff() and owner_id = auth.uid());

-- appointments ---------------------------------------------------------------------
create policy "appointments patient read" on public.appointments
  for select using (public.is_appointment_owner(id));

create policy "appointments doctor read" on public.appointments
  for select using (public.is_appointment_doctor(id));

create policy "appointments branch staff read" on public.appointments
  for select using (public.is_branch_staff() and branch_id = public.current_branch_id());

create policy "appointments patient insert" on public.appointments
  for insert with check (
    public.is_patient_owner(patient_id)
    and doctor_id is not null
    and branch_id is not null
    and public.doctor_posts_at(doctor_id, branch_id)
  );

create policy "appointments branch staff insert" on public.appointments
  for insert with check (public.is_branch_staff() and branch_id = public.current_branch_id());

create policy "appointments patient update" on public.appointments
  for update
  using (public.is_appointment_owner(id))
  with check (
    public.is_appointment_owner(id)
    and status in ('pending', 'confirmed', 'cancelled')
    and doctor_id = (select old.doctor_id from public.appointments old where old.id = appointments.id)
    and branch_id = (select old.branch_id from public.appointments old where old.id = appointments.id)
    and patient_id = (select old.patient_id from public.appointments old where old.id = appointments.id)
  );

create policy "appointments doctor update" on public.appointments
  for update
  using (public.is_appointment_doctor(id))
  with check (
    public.is_appointment_doctor(id)
    and doctor_id = (select old.doctor_id from public.appointments old where old.id = appointments.id)
    and branch_id = (select old.branch_id from public.appointments old where old.id = appointments.id)
    and patient_id = (select old.patient_id from public.appointments old where old.id = appointments.id)
  );

create policy "appointments branch staff update" on public.appointments
  for update
  using (public.is_branch_staff() and branch_id = public.current_branch_id())
  with check (public.is_branch_staff() and branch_id = public.current_branch_id());

create policy "appointments branch staff delete" on public.appointments
  for delete using (public.is_branch_staff() and branch_id = public.current_branch_id());

-- queue numbers are computed by public.next_queue_number() (counts the caller's
-- visible appointments), so no queue_counters table/policies exist by design.

-- prescriptions --------------------------------------------------------------------
create policy "prescriptions patient read" on public.prescriptions
  for select using (public.is_appointment_owner(appointment_id));

create policy "prescriptions doctor read" on public.prescriptions
  for select using (public.is_appointment_doctor(appointment_id));

create policy "prescriptions branch staff read" on public.prescriptions
  for select using (public.is_branch_staff() and public.is_appointment_at_my_branch(appointment_id));

create policy "prescriptions doctor insert" on public.prescriptions
  for insert with check (
    public.doctor_owns_prescription(appointment_id, doctor_id, patient_id)
    and public.appointment_belongs_to_patient(appointment_id, patient_id)
  );

create policy "prescriptions doctor update" on public.prescriptions
  for update
  using (public.is_appointment_doctor(appointment_id))
  with check (public.doctor_owns_prescription(appointment_id, doctor_id, patient_id));

-- medical_records ------------------------------------------------------------------
create policy "records patient read" on public.medical_records
  for select using (public.is_patient_owner(patient_id));

create policy "records assigned doctor read" on public.medical_records
  for select using (public.is_patient_assigned_doctor(patient_id));

create policy "records branch staff read" on public.medical_records
  for select using (public.is_branch_staff() and public.patient_at_my_branch(patient_id));

create policy "records patient insert" on public.medical_records
  for insert with check (public.is_patient_owner(patient_id) and uploaded_by = auth.uid());

create policy "records staff insert" on public.medical_records
  for insert with check (public.is_branch_staff() and public.patient_at_my_branch(patient_id));

create policy "records owner update" on public.medical_records
  for update
  using (uploaded_by = auth.uid() or public.is_patient_owner(patient_id))
  with check (
    patient_id = (select old.patient_id from public.medical_records old where old.id = medical_records.id)
    and uploaded_by = (select old.uploaded_by from public.medical_records old where old.id = medical_records.id)
  );

create policy "records owner delete" on public.medical_records
  for delete using (uploaded_by = auth.uid());

-- services / announcements --------------------------------------------------------
create policy "services public read" on public.services
  for select using (true);

create policy "services branch write" on public.services
  for all
  using (public.is_branch_staff() and branch_id = public.current_branch_id())
  with check (public.is_branch_staff() and branch_id = public.current_branch_id());

create policy "announcements public read active" on public.announcements
  for select using (
    (starts_at is null or starts_at <= now())
    and (ends_at is null or ends_at >= now())
  );

create policy "announcements staff read" on public.announcements
  for select using (public.is_staff() and (branch_id is null or branch_id = public.current_branch_id()));

create policy "announcements branch staff write" on public.announcements
  for all
  using (public.is_branch_staff() and branch_id = public.current_branch_id())
  with check (public.is_branch_staff() and branch_id = public.current_branch_id());

-- notifications (patient owns their inbox; staff write within branch) -------------
create policy "notifications owner read" on public.notifications
  for select using (user_id = auth.uid());

create policy "notifications branch staff insert" on public.notifications
  for insert with check (public.is_branch_staff());

create policy "notifications owner update" on public.notifications
  for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "notifications owner delete" on public.notifications
  for delete using (user_id = auth.uid());

-- reviews --------------------------------------------------------------------------
create policy "reviews public read approved" on public.reviews
  for select using (is_approved = true);

create policy "reviews author read" on public.reviews
  for select using (public.is_patient_owner(patient_id));

create policy "reviews patient insert" on public.reviews
  for insert with check (public.is_patient_owner(patient_id) and public.is_appointment_owner(appointment_id));

create policy "reviews author update" on public.reviews
  for update
  using (public.is_patient_owner(patient_id))
  with check (public.is_patient_owner(patient_id) and is_approved = false);

create policy "reviews staff approve" on public.reviews
  for update
  using (public.is_staff())
  with check (
    public.is_staff()
    and patient_id = (select old.patient_id from public.reviews old where old.id = reviews.id)
    and appointment_id = (select old.appointment_id from public.reviews old where old.id = reviews.id)
  );

-- payments (Razorpay: patients see their own; staff manage at branch) ------------
create policy "payments patient read" on public.payments
  for select using (public.is_appointment_owner(appointment_id));

create policy "payments branch staff read" on public.payments
  for select using (public.is_branch_staff() and public.is_appointment_at_my_branch(appointment_id));

create policy "payments branch staff insert" on public.payments
  for insert
  with check (
    public.is_branch_staff()
    and public.is_appointment_at_my_branch(appointment_id)
    and status in ('unpaid', 'paid')
  );

create policy "payments branch staff update" on public.payments
  for update
  using (public.is_branch_staff() and public.is_appointment_at_my_branch(appointment_id))
  with check (public.is_branch_staff() and public.is_appointment_at_my_branch(appointment_id));

-- audit_logs (written by the postgres/service role; only super_admin reads) -------
create policy "audit super read" on public.audit_logs
  for select using (public.current_role() = 'super_admin');

create policy "audit super insert" on public.audit_logs
  for insert with check (public.current_role() = 'super_admin');

-- super_admin: full access on every table ----------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'branches', 'profiles', 'departments', 'doctors', 'doctor_branches',
    'patients', 'appointments', 'prescriptions',
    'medical_records', 'doctor_schedules', 'doctor_time_off', 'services',
    'announcements', 'notifications', 'reviews', 'payments', 'audit_logs'
  ]
  loop
    execute format(
      'create policy "super all" on public.%I for all using (public.current_role() = ''super_admin'') with check (public.current_role() = ''super_admin'')',
      t
    );
  end loop;
end $$;

-- Storage buckets + object policies (Module 3) -------------------------------------
do $$
begin
  if to_regnamespace('storage') is null then
    raise notice 'storage schema not present (pure Postgres test) — skipping bucket policies';
    return;
  end if;

  insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
  values
    ('avatars', 'avatars', false, 5242880, array['image/png', 'image/jpeg', 'image/webp']),
    ('doctor-photos', 'doctor-photos', true, 5242880, array['image/png', 'image/jpeg', 'image/webp']),
    ('medical-records', 'medical-records', false, 20971520, array['image/png', 'image/jpeg', 'image/webp', 'application/pdf']),
    ('prescriptions', 'prescriptions', false, 20971520, array['image/png', 'image/jpeg', 'image/webp', 'application/pdf'])
  on conflict (id) do nothing;

  -- avatars: everyone may read; only the owner may write inside their own folder.
  drop policy if exists "avatars public read" on storage.objects;
  create policy "avatars public read" on storage.objects
    for select using (bucket_id = 'avatars');

  drop policy if exists "avatars owner write" on storage.objects;
  create policy "avatars owner write" on storage.objects
    for all
    using (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1])
    with check (bucket_id = 'avatars' and auth.uid()::text = (storage.foldername(name))[1]);

  -- doctor-photos: public catalog reads; owning doctor or staff may write.
  drop policy if exists "doctor photos read" on storage.objects;
  create policy "doctor photos read" on storage.objects
    for select using (bucket_id = 'doctor-photos');

  drop policy if exists "doctor photos write" on storage.objects;
  create policy "doctor photos write" on storage.objects
    for all
    using (
      bucket_id = 'doctor-photos'
      and (
        public.is_staff()
        or exists (
          select 1 from public.doctors d
          where d.profile_id = auth.uid() and d.id::text = (storage.foldername(name))[1]
        )
      )
    )
    with check (
      bucket_id = 'doctor-photos'
      and (
        public.is_staff()
        or exists (
          select 1 from public.doctors d
          where d.profile_id = auth.uid() and d.id::text = (storage.foldername(name))[1]
        )
      )
    );

  -- medical-records / prescriptions: private, patient-foldered via helper predicate.
  drop policy if exists "records folder read" on storage.objects;
  create policy "records folder read" on storage.objects
    for select using (bucket_id = 'medical-records' and public.storage_patient_access((storage.foldername(name))[1]));

  drop policy if exists "records folder write" on storage.objects;
  create policy "records folder write" on storage.objects
    for all
    using (bucket_id = 'medical-records' and public.storage_patient_access((storage.foldername(name))[1]))
    with check (bucket_id = 'medical-records' and public.storage_patient_access((storage.foldername(name))[1]));

  drop policy if exists "prescriptions folder read" on storage.objects;
  create policy "prescriptions folder read" on storage.objects
    for select using (bucket_id = 'prescriptions' and public.storage_patient_access((storage.foldername(name))[1]));

  drop policy if exists "prescriptions folder write" on storage.objects;
  create policy "prescriptions folder write" on storage.objects
    for all
    using (bucket_id = 'prescriptions' and public.storage_patient_access((storage.foldername(name))[1]))
    with check (bucket_id = 'prescriptions' and public.storage_patient_access((storage.foldername(name))[1]));
end $$;

-- ======== 0008_doctor_discovery.sql ========
-- Module 6: one denormalized public doctor row avoids catalog N+1 queries.
-- Security invoker preserves the underlying doctors/departments RLS policies.
drop view if exists public.doctor_listing_view;
create view public.doctor_listing_view as
select d.id, d.profile_id, d.department_id, d.medicine_type, d.full_name, d.full_name_bn,
       d.slug, d.bio, d.qualifications, d.specialties, d.experience_years,
       d.registration_no, d.photo_url, d.languages, d.rating_avg, d.rating_count,
       d.telemedicine_enabled, d.is_active, dep.name as department_name,
       dep.name_bn as department_name_bn,
       (select min(db.consultation_fee) from public.doctor_branches db where db.doctor_id = d.id and db.branch_id is not null) as min_fee,
       (select jsonb_agg(jsonb_build_object('id', db.id, 'branchId', db.branch_id,
         'consultationFee', db.consultation_fee, 'followupFee', db.followup_fee,
         'followupValidDays', db.followup_valid_days, 'telemedicineFee', db.telemedicine_fee,
         'roomNo', db.room_no) order by db.consultation_fee)
        from public.doctor_branches db where db.doctor_id = d.id) as branches,
       (select jsonb_agg(jsonb_build_object('id', s.id, 'doctorBranchId', s.doctor_branch_id,
         'weekday', s.weekday, 'startTime', s.start_time, 'endTime', s.end_time,
         'slotMinutes', s.slot_minutes, 'maxPerSlot', s.max_per_slot)
        order by s.weekday, s.start_time)
        from public.doctor_schedules s join public.doctor_branches db2 on db2.id = s.doctor_branch_id
        where db2.doctor_id = d.id and s.is_active) as schedules
from public.doctors d
left join public.departments dep on dep.id = d.department_id;

grant select on public.doctor_listing_view to anon, authenticated;

-- ======== 0009_admin_control.sql ========
﻿-- Module 11 global control settings and CMS content.
create table if not exists public.site_settings (key text primary key, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.content_pages (id uuid primary key default gen_random_uuid(), slug text unique not null, kind text not null check (kind in ('faq','health_tip','homepage_banner')), title text not null, title_bn text, body text, body_bn text, metadata jsonb not null default '{}'::jsonb, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.site_settings enable row level security; alter table public.content_pages enable row level security;
drop policy if exists "settings super all" on public.site_settings; create policy "settings super all" on public.site_settings for all using (public.current_role() = 'super_admin') with check (public.current_role() = 'super_admin');
drop policy if exists "content public active" on public.content_pages; create policy "content public active" on public.content_pages for select using (is_active = true);
drop policy if exists "content super all" on public.content_pages; create policy "content super all" on public.content_pages for all using (public.current_role() = 'super_admin') with check (public.current_role() = 'super_admin');
insert into public.site_settings (key, value) values ('site', '{"paymentMethods":["counter","bkash","nagad","card"],"bookingFee":0,"cancellationWindowHours":6,"slotHoldMinutes":5,"emergencyPhones":["16263"]}'::jsonb) on conflict (key) do nothing;

-- ======== 0010_payments.sql ========
﻿-- Module 12 payment hardening: receipts, idempotency and provider methods.
alter table public.payments add column if not exists receipt_number text;
create unique index if not exists payments_provider_ref_unique on public.payments(provider_ref) where provider_ref is not null;
alter table public.payments drop constraint if exists payments_method_check;
alter table public.payments add constraint payments_method_check check (method in ('cash','bkash','nagad','card','sslcommerz'));

-- ======== 0011_wow_features.sql ========
﻿-- Module 13 feature flags and optional wow-layer settings.
insert into public.site_settings (key, value) values ('features', '{"aiSymptomHelper":true,"smartSlotRecommender":true,"queuePrediction":true,"qrKiosk":true,"telemedicine":true,"medicineReminders":true,"healthTools":true,"voiceInput":true,"smartRouting":true,"visual3d":true,"nightCare":true,"highContrast":true,"fontSize":true,"whatsappShare":true,"blog":true,"equeuePush":true}'::jsonb) on conflict (key) do nothing;

-- ======== 0012_realtime.sql ========
-- Module 16: Realtime queue updates for appointment and notification consumers.
do $$ begin
  alter publication supabase_realtime add table public.appointments;
exception when duplicate_object then null; when undefined_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; when undefined_object then null; end $$;

-- ======== 0013_profile_provisioning.sql ========
-- ============================================================================
-- Module 13: profile provisioning for every signup.
-- Run AFTER 0012_realtime.sql. Idempotent.
--
-- Gap this closes: 0003_functions.sql creates only a minimal profile row
-- (id, full_name, role, preferred_lang) and never a `patients` record.
-- Consequences before this migration:
--   * phone / avatar / language captured at signup were discarded
--   * a patient could sign in but had no public.patients row, so booking,
--     prescriptions, records and family members all resolved to nothing
--   * staff (receptionist / branch_admin / super_admin) had no supported
--     path at all - only the doctor branch in admin.ts provisioned them
--   * users who signed up before the trigger existed had no profile at all
-- ============================================================================

-- 1. Upgrade the signup trigger ----------------------------------------------
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_full_name text;
  v_phone     text;
  v_lang      text;
  v_role      public.user_role;
begin
  v_full_name := coalesce(
    nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
    nullif(trim(split_part(coalesce(new.email, ''), '@', 1)), ''),
    'New user'
  );
  v_phone := nullif(trim(coalesce(new.raw_user_meta_data ->> 'phone', '')), '');
  -- Only 'en'/'bn' are allowed by the profiles check constraint.
  v_lang := case when new.raw_user_meta_data ->> 'preferred_lang' = 'bn' then 'bn' else 'en' end;

  -- Self-service signup is always a patient. Privileged roles are granted
  -- server-side by an admin, never from client-controlled metadata.
  v_role := 'patient';

  insert into public.profiles (id, full_name, phone, role, preferred_lang, avatar_url)
  values (new.id, v_full_name, v_phone, v_role, v_lang,
          nullif(trim(coalesce(new.raw_user_meta_data ->> 'avatar_url', '')), ''))
  on conflict (id) do update set
    full_name     = excluded.full_name,
    phone         = coalesce(excluded.phone, public.profiles.phone),
    preferred_lang= excluded.preferred_lang,
    updated_at    = now();

  -- Give every patient a public.patients row so booking and records resolve.
  -- public.patients has no unique constraint on owner_id (one account may
  -- manage several family members), so guard with NOT EXISTS; ON CONFLICT
  -- would never match and would insert duplicate rows.
  if v_role = 'patient' then
    insert into public.patients (owner_id, full_name, phone)
    select new.id, v_full_name, v_phone
    where not exists (
      select 1 from public.patients p
      where p.owner_id = new.id and p.full_name = v_full_name
    );
  end if;

  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2. Backfill every auth user that predates this trigger ----------------------
-- Without this, anyone who signed up before the trigger existed (or while it
-- was broken) has no profile and lands in AuthProvider's 'patient' fallback
-- with a blank name.

insert into public.profiles (id, full_name, phone, role, preferred_lang)
select
  au.id,
  coalesce(
    nullif(trim(au.raw_user_meta_data ->> 'full_name'), ''),
    nullif(trim(au.raw_user_meta_data ->> 'name'), ''),
    nullif(trim(split_part(coalesce(au.email, ''), '@', 1)), ''),
    'New user'
  ),
  nullif(trim(coalesce(au.raw_user_meta_data ->> 'phone', '')), ''),
  -- Never elevate from client metadata: default everyone to patient.
  'patient'::public.user_role,
  case when au.raw_user_meta_data ->> 'preferred_lang' = 'bn' then 'bn' else 'en' end
from auth.users au
where not exists (select 1 from public.profiles p where p.id = au.id)
on conflict (id) do nothing;

-- 3. Backfill the missing patients rows for existing patient profiles --------
insert into public.patients (owner_id, full_name, phone)
select p.id, coalesce(p.full_name, 'New user'), p.phone
from public.profiles p
where p.role = 'patient'
  and not exists (
    select 1 from public.patients pt
    where pt.owner_id = p.id and pt.full_name = coalesce(p.full_name, 'New user')
  );

