import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { MapPin, Phone, Navigation } from 'lucide-react';
import { apiGet } from '@/lib/api';
import type { Branch } from '@/lib/catalog';
import { GlassCard } from '@/components/Button';
import { EmptyState, ErrorState, Skeleton } from '@/components/feedback';
export function BranchesPage(){const {t,i18n}=useTranslation('common');const bn=i18n.language==='bn';const [city,setCity]=useState('');const q=useQuery({queryKey:['branches'],queryFn:()=>apiGet<{data:Branch[]}>('/v1/branches')});const data=(q.data?.data??[]).filter(x=>!city||x.city.toLowerCase()===city);return <div className="space-y-5"><Helmet><title>Branches — MediNova</title></Helmet><h1 className="text-3xl font-extrabold">Our branches</h1><div className="glass p-4"><select value={city} onChange={e=>setCity(e.target.value.toLowerCase())} className="rounded-xl border bg-card p-3"><option value="">All cities</option>{[...new Set((q.data?.data??[]).map(x=>x.city))].map(x=><option key={x}>{x}</option>)}</select></div>{q.isPending?<div className="grid gap-4 md:grid-cols-2">{[1,2,3,4].map(i=><Skeleton className="h-52" key={i}/>)}</div>:q.isError?<ErrorState message={t('error')} onRetry={()=>q.refetch()}/>:!data.length?<EmptyState title={t('empty')}/>:<div className="grid gap-4 md:grid-cols-2">{data.map(b=><GlassCard key={b.id}><div className="flex justify-between"><h2 className="text-lg font-extrabold">{bn?b.nameBn:b.name}</h2><a href={`tel:${b.phone}`} aria-label="Call branch"><Phone size={18} className="text-primary"/></a></div><p className="mt-2 text-sm opacity-70"><MapPin size={15} className="mr-1 inline"/>{bn?b.addressBn:b.address}, {b.city}</p><div className="mt-4 h-32 overflow-hidden rounded-xl bg-muted"><iframe title={`Map of ${b.name}`} src={`https://www.openstreetmap.org/export/embed.html?bbox=${b.lng-0.01}%2C${b.lat-0.01}%2C${b.lng+0.01}%2C${b.lat+0.01}&layer=mapnik&marker=${b.lat}%2C${b.lng}`} className="h-full w-full" loading="lazy"/></div><a href={`https://www.google.com/maps/search/?api=1&query=${b.lat},${b.lng}`} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-primary">Directions <Navigation size={15}/></a></GlassCard>)}</div>}</div>}
