import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { useMemo, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { Search, PhoneCall, Ambulance, ChevronDown, Star, ArrowRight } from 'lucide-react';
import { apiGet, formatBdt } from '@/lib/api';
import type { Branch, Department, Doctor } from '@/lib/catalog';
import { GlassCard } from '@/components/Button';
import { Skeleton } from '@/components/feedback';

// HomePage content lives in the `home` locale namespace (en + bn). Every
// user-visible string MUST come from i18n: this file previously hardcoded
// Bengali inline, and those literals were silently corrupted into replacement
// runs, which shipped garbage to every Bengali visitor.

export function HomePage(){
 const [search,setSearch]=useState(''); const [open,setOpen]=useState(0); const reduce=useReducedMotion();
 const {t,i18n}=useTranslation(['home']); const bn=i18n.language==='bn';
 const branches=useQuery({queryKey:['branches'],queryFn:()=>apiGet<{data:Branch[]}>('/v1/branches')});
 const depts=useQuery({queryKey:['departments'],queryFn:()=>apiGet<{data:Department[]}>('/v1/departments')});
 const doctors=useQuery({queryKey:['doctors'],queryFn:()=>apiGet<{data:Doctor[]}>('/v1/doctors')});
 const results=useMemo(()=>[...(branches.data?.data??[]).map(x=>({...x,kind:'branch'})),...(depts.data?.data??[]).map(x=>({...x,kind:'department',name:bn?x.nameBn:x.name})),...(doctors.data?.data??[]).map(x=>({...x,kind:'doctor',name:bn?x.fullNameBn:x.fullName}))].filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).slice(0,6),[branches.data,depts.data,doctors.data,search,bn]);
 return <div className="space-y-10"><Helmet><title>{t('title')} · MediNova</title><meta name="description" content="Find doctors, branches and affordable health packages at MediNova."/></Helmet>
 <section className="mesh-hero grain relative overflow-hidden rounded-3xl p-8 md:p-14"><motion.div initial={reduce?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} className="relative z-[2] max-w-3xl"><span className="glass px-3 py-1 text-xs font-bold">{t('badge')}</span><h1 className="mt-4 text-4xl font-extrabold leading-tight md:text-6xl"><span className="text-gradient">{t('title')}</span></h1><p className="mt-3 max-w-xl text-base opacity-80 md:text-lg">{t('subtitle')}</p><div className="relative mt-7 max-w-xl"><Search className="absolute left-4 top-4 text-primary" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('searchPlaceholder')} className="w-full rounded-2xl border bg-card py-3 pl-12 pr-4 shadow-lg"/><Link to="/doctors" className="btn-gradient absolute right-2 top-1 rounded-xl px-4 py-2.5">{t('searchCta')}</Link>{search&&<div className="glass absolute left-0 right-0 top-14 z-30 p-2 shadow-xl">{results.length?results.map((r,i)=><Link key={`${r.kind}-${(r as any).id}-${i}`} to={r.kind==='doctor'?'/doctors':r.kind==='branch'?'/branches':'/departments'} className="block rounded-lg px-3 py-2 text-sm hover:bg-muted">{r.name}<span className="float-right text-xs opacity-50">{r.kind}</span></Link>):<p className="p-3 text-sm opacity-70">{t('noMatches')}</p>}</div>}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/book" className="btn-gradient glow rounded-xl px-6 py-3">{t('ctaBook')}</Link><Link to="/branches" className="glass rounded-xl px-6 py-3 font-bold">{t('ctaExplore')}</Link></div></motion.div></section>
 <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900 dark:bg-red-950/30 dark:text-red-200"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-extrabold">{t('emergencyTitle')}</p><p className="text-sm opacity-80">{t('emergencyBody')}</p></div><div className="flex gap-2"><a href="tel:16263" className="btn-gradient inline-flex items-center gap-2 rounded-xl px-4 py-2"><PhoneCall size={18}/> 16263</a><Link to="/contact?type=ambulance" className="glass inline-flex items-center gap-2 rounded-xl px-4 py-2 font-bold"><Ambulance size={18}/> {t('requestAmbulance')}</Link></div></div></div>
 <section><SectionTitle title={t('departments')} action="/departments" label={t('viewAll')}/><div className="grid gap-4 md:grid-cols-3">{depts.isPending?[1,2,3].map(i=><Skeleton className="h-28" key={i}/>):depts.data?.data.slice(0,6).map(d=><GlassCard key={d.id}><span className="text-xs font-bold uppercase text-primary">{d.medicineType}</span><h3 className="mt-1 text-lg font-bold">{bn?d.nameBn:d.name}</h3><p className="mt-1 line-clamp-2 text-sm opacity-70">{d.description}</p></GlassCard>)}</div></section>
 <section><SectionTitle title={t('featuredDoctors')} action="/doctors" label={t('viewAll')}/><div className="grid gap-4 md:grid-cols-3">{doctors.isPending?[1,2,3].map(i=><Skeleton className="h-48" key={i}/>):doctors.data?.data.slice(0,3).map(d=><DoctorCard key={d.id} d={d} bn={bn} t={t}/>)}</div></section>
 <section><h2 className="text-2xl font-extrabold">{t('featuresTitle')}</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{(['fees','slots','language'] as const).map(k=><GlassCard key={k}><p className="text-sm font-bold">{t(`features.${k}.title`)}</p><p className="mt-1 text-sm opacity-70">{t(`features.${k}.body`)}</p></GlassCard>)}</div></section>
 <section><SectionTitle title={t('packages')} action="/packages" label={t('viewAll')}/><PackageCards bn={bn} t={t}/></section>
  <section><h2 className="text-2xl font-extrabold">{t('faqTitle')}</h2><div className="mt-4 space-y-2">{(t('faqs', { returnObjects: true }) as Array<{ q: string; a: string }>).map((f, i) => <div className="glass p-4" key={f.q}><button className="flex w-full justify-between text-left font-bold" onClick={() => setOpen(open === i ? -1 : i)}>{f.q}<ChevronDown size={18} className={open === i ? 'rotate-180 transition' : 'transition'} /></button>{open === i && <p className="mt-2 text-sm opacity-75">{f.a}</p>}</div>)}</div></section>
  {/* Buyer-facing hook: the patient homepage is the first thing a clinic
      owner sees, so it has to answer "is this something I can run?" too. */}
  <section className="mesh-hero grain relative overflow-hidden rounded-3xl border border-primary/30 p-6 md:p-10"><div className="relative z-[2] flex flex-wrap items-center justify-between gap-4"><div className="max-w-xl"><h2 className="text-xl font-extrabold md:text-2xl">{t('forClinics')}</h2><p className="mt-2 text-sm opacity-80 md:text-base">{t('forClinicsBody')}</p></div><div className="flex flex-wrap gap-3"><Link to="/demo" className="glass rounded-xl px-6 py-3 font-extrabold">{t('nav:demo')}</Link><Link to="/pricing" className="btn-gradient rounded-xl px-6 py-3 font-extrabold">{t('nav:pricing')}</Link></div></div></section>
 </div>
}
function SectionTitle({title,action,label}:{title:string;action:string;label:string}){return <div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-extrabold">{title}</h2><Link to={action} className="flex items-center gap-1 text-sm font-bold text-primary">{label}<ArrowRight size={16}/></Link></div>}
function DoctorCard({d,bn,t}:{d:Doctor;bn:boolean;t:(k:string)=>string}){return <GlassCard><div className="flex gap-3">{d.photoUrl?<img src={d.photoUrl} alt="" className="h-20 w-20 rounded-2xl object-cover"/>:<div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-primary/10 text-2xl">??</div>}<div><h3 className="font-bold">{bn?d.fullNameBn:d.fullName}</h3><p className="mt-1 text-xs uppercase text-primary">{d.medicineType}</p><p className="mt-2 flex items-center gap-1 text-sm"><Star size={14} className="fill-amber-400 text-amber-400"/> {d.ratingAvg?.toFixed(1)} <span className="opacity-50">({d.ratingCount??0})</span></p></div></div><div className="mt-4 flex items-center justify-between"><span className="font-bold">{d.fees[0] ? formatBdt(d.fees[0].consultationFee, bn?'bn':'en') : t('feeOnRequest')}</span><Link to="/doctors" className="text-sm font-bold text-primary">{t('viewProfile')}</Link></div></GlassCard>}
function PackageCards({bn,t}:{bn:boolean;t:(k:string)=>string}){return <div className="grid gap-4 md:grid-cols-3">{['Executive Health','Family Screening','Women Wellness'].map((x,i)=><GlassCard key={x}><p className="font-extrabold">{x}</p><p className="mt-1 text-sm opacity-70">{t('packagesDesc')}</p><p className="mt-4 text-xl font-extrabold">{formatBdt([4500,6500,3800][i], bn?'bn':'en')}</p><Link to="/packages" className="mt-4 block text-center btn-gradient rounded-xl py-2">{t('comparePackages')}</Link></GlassCard>)}</div>}
