import { useQuery } from '@tanstack/react-query';
import { Helmet } from 'react-helmet-async';
import { useMemo, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { Search, PhoneCall, Ambulance, ChevronDown, Star, ArrowRight } from 'lucide-react';
import { apiGet, formatBdt } from '@/lib/api';
import type { Branch, Department, Doctor } from '@/lib/catalog';
import { GlassCard } from '@/components/Button';
import { Skeleton } from '@/components/feedback';

const faqs = { en:[['How do I book an appointment?','Choose a doctor and branch, then select an available slot from the booking page.'],['Can I consult at home?','Yes. Doctors with telemedicine enabled can be booked for an online visit.'],['What payment methods are accepted?','You can pay online or at the branch. Fees are shown in BDT before booking.'],['How do I request an ambulance?','Call the emergency hotline immediately or use the ambulance request link below.']], bn:[['???????????????? ?????? ??? ????','??????? ? ???? ???? ????? ????? ??? ???? ?????? ???? ???? ????'],['??????? ????????? ????','?????? ??????????? ???? ?????????? ????? ??????? ??? ??? ?????'],['??? ??????? ?????? ????','??????? ?? ?????? ??????? ??? ????? ????????? ??? ?? ???? ?????'],['????????????? ?????? ?????','???? ????? ??????? ?? ???? ???? ????? ????????????? ?????? ??????? ?????']] };

export function HomePage(){
 const [search,setSearch]=useState(''); const [open,setOpen]=useState(0); const reduce=useReducedMotion();
 const {t,i18n}=useTranslation(['home']); const bn=i18n.language==='bn';
 const branches=useQuery({queryKey:['branches'],queryFn:()=>apiGet<{data:Branch[]}>('/v1/branches')});
 const depts=useQuery({queryKey:['departments'],queryFn:()=>apiGet<{data:Department[]}>('/v1/departments')});
 const doctors=useQuery({queryKey:['doctors'],queryFn:()=>apiGet<{data:Doctor[]}>('/v1/doctors')});
 const results=useMemo(()=>[...(branches.data?.data??[]).map(x=>({...x,kind:'branch'})),...(depts.data?.data??[]).map(x=>({...x,kind:'department',name:bn?x.nameBn:x.name})),...(doctors.data?.data??[]).map(x=>({...x,kind:'doctor',name:bn?x.fullNameBn:x.fullName}))].filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).slice(0,6),[branches.data,depts.data,doctors.data,search,bn]);
 return <div className="space-y-10"><Helmet><title>MediNova � Care that feels like the future</title><meta name="description" content="Find doctors, branches and affordable health packages at MediNova."/></Helmet>
 <section className="mesh-hero grain relative overflow-hidden rounded-3xl p-8 md:p-14"><motion.div initial={reduce?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} className="relative z-[2] max-w-3xl"><span className="glass px-3 py-1 text-xs font-bold">{t('badge')}</span><h1 className="mt-4 text-4xl font-extrabold leading-tight md:text-6xl"><span className="text-gradient">{t('title')}</span></h1><p className="mt-3 max-w-xl text-base opacity-80 md:text-lg">{t('subtitle')}</p><div className="relative mt-7 max-w-xl"><Search className="absolute left-4 top-4 text-primary" size={20}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={bn?'???????, ????? ?? ?????? ??????�':'Search doctor, department or symptom�'} className="w-full rounded-2xl border bg-card py-3 pl-12 pr-4 shadow-lg"/><Link to="/doctors" className="btn-gradient absolute right-2 top-1 rounded-xl px-4 py-2.5">{bn?'??????':'Search'}</Link>{search&&<div className="glass absolute left-0 right-0 top-14 z-30 p-2 shadow-xl">{results.length?results.map((r,i)=><Link key={`${r.kind}-${(r as any).id}-${i}`} to={r.kind==='doctor'?'/doctors':r.kind==='branch'?'/branches':'/departments'} className="block rounded-lg px-3 py-2 text-sm hover:bg-muted">{r.name}<span className="float-right text-xs opacity-50">{r.kind}</span></Link>):<p className="p-3 text-sm opacity-70">{bn?'???? ?????? ??????':'No matches'}</p>}</div>}</div><div className="mt-8 flex flex-wrap gap-3"><Link to="/book" className="btn-gradient glow rounded-xl px-6 py-3">{t('ctaBook')}</Link><Link to="/branches" className="glass rounded-xl px-6 py-3 font-bold">{t('ctaExplore')}</Link></div></motion.div></section>
 <div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900 dark:bg-red-950/30 dark:text-red-200"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-extrabold">24/7 emergency support</p><p className="text-sm opacity-80">Call our hotline or request an ambulance for safe transport.</p></div><div className="flex gap-2"><a href="tel:16263" className="btn-gradient inline-flex items-center gap-2 rounded-xl px-4 py-2"><PhoneCall size={18}/> 16263</a><Link to="/contact?type=ambulance" className="glass inline-flex items-center gap-2 rounded-xl px-4 py-2 font-bold"><Ambulance size={18}/> Request ambulance</Link></div></div></div>
 <section><SectionTitle title="Departments" action="/departments" bn={bn}/><div className="grid gap-4 md:grid-cols-3">{depts.isPending?[1,2,3].map(i=><Skeleton className="h-28" key={i}/>):depts.data?.data.slice(0,6).map(d=><GlassCard key={d.id}><span className="text-xs font-bold uppercase text-primary">{d.medicineType}</span><h3 className="mt-1 text-lg font-bold">{bn?d.nameBn:d.name}</h3><p className="mt-1 line-clamp-2 text-sm opacity-70">{d.description}</p></GlassCard>)}</div></section>
 <section><SectionTitle title="Featured doctors" action="/doctors" bn={bn}/><div className="grid gap-4 md:grid-cols-3">{doctors.isPending?[1,2,3].map(i=><Skeleton className="h-48" key={i}/>):doctors.data?.data.slice(0,3).map(d=><DoctorCard key={d.id} d={d} bn={bn}/>)}</div></section>
 <section className="grid gap-4 md:grid-cols-3"><GlassCard><p className="text-sm font-bold">Transparent fees</p><p className="mt-1 text-sm opacity-70">See BDT pricing before you book.</p></GlassCard><GlassCard><p className="text-sm font-bold">Real-time slots</p><p className="mt-1 text-sm opacity-70">Choose only available appointment times.</p></GlassCard><GlassCard><p className="text-sm font-bold">Your language</p><p className="mt-1 text-sm opacity-70">English and Bengali, end to end.</p></GlassCard></section>
 <section><SectionTitle title="Health packages" action="/packages" bn={bn}/><PackageCards bn={bn}/></section>
 <section><h2 className="text-2xl font-extrabold">Frequently asked questions</h2><div className="mt-4 space-y-2">{faqs[bn?'bn':'en'].map(([q,a],i)=><div className="glass p-4" key={q}><button className="flex w-full justify-between text-left font-bold" onClick={()=>setOpen(open===i?-1:i)}>{q}<ChevronDown size={18}/></button>{open===i&&<p className="mt-2 text-sm opacity-75">{a}</p>}</div>)}</div></section>
 </div>
}
function SectionTitle({title,action,bn}:{title:string;action:string;bn:boolean}){return <div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-extrabold">{title}</h2><Link to={action} className="flex items-center gap-1 text-sm font-bold text-primary">{bn?'?? ?????':'View all'}<ArrowRight size={16}/></Link></div>}
function DoctorCard({d,bn}:{d:Doctor;bn:boolean}){return <GlassCard><div className="flex gap-3">{d.photoUrl?<img src={d.photoUrl} alt="" className="h-20 w-20 rounded-2xl object-cover"/>:<div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-primary/10 text-2xl">??</div>}<div><h3 className="font-bold">{bn?d.fullNameBn:d.fullName}</h3><p className="mt-1 text-xs uppercase text-primary">{d.medicineType}</p><p className="mt-2 flex items-center gap-1 text-sm"><Star size={14} className="fill-amber-400 text-amber-400"/> {d.ratingAvg?.toFixed(1)} <span className="opacity-50">({d.ratingCount??0})</span></p></div></div><div className="mt-4 flex items-center justify-between"><span className="font-bold">{d.fees[0]?formatBdt(d.fees[0].consultationFee,bn?'bn':'en'):'�'}</span><Link to="/doctors" className="text-sm font-bold text-primary">View profile</Link></div></GlassCard>}
function PackageCards({bn}:{bn:boolean}){return <div className="grid gap-4 md:grid-cols-3">{['Executive Health','Family Screening','Women Wellness'].map((x,i)=><GlassCard key={x}><p className="font-extrabold">{x}</p><p className="mt-1 text-sm opacity-70">{bn?'??????? ? ?????????? ???????':'Tests and specialist consultation'}</p><p className="mt-4 text-xl font-extrabold">?{[4500,6500,3800][i]}</p><Link to="/packages" className="mt-4 block text-center btn-gradient rounded-xl py-2">Compare packages</Link></GlassCard>)}</div>}
